### PR TITLE
Fix/proj 8007

### PR DESCRIPTION
**Pull request by ivan-shtyrlyaev-nitka**

### CODE REVIEW

**Review by rbvea — CHANGES_REQUESTED** [review]
I've tested this on `develop` and it looks like it breaks existing functionality, the dropdown values should stay instead of disappear, also note the time where there are two "hawaii" values present perhaps we shouldn't use VAS for the combination input at all 🤔 

https://github.com/politico/vue-accessible-selects/assets/949055/d0e61154-98c9-41dd-a916-a7411d1d62f1

**Comment by ivan-shtyrlyaev-nitka** [comment]
> I've tested this on `develop` and it looks like it breaks existing functionality, the dropdown values should stay instead of disappear, also note the time where there are two "hawaii" values present perhaps we shouldn't use VAS for the combination input at all 🤔
> 
>  Screen.Recording.2023-12-18.at.3.55.43.PM.mov

@rbvea please note,  changes here are fixing nothing but using `uniqueIdField` instead of hardcoded `value`.
If you think we should keep selected options - this is a requirement for the new task. It's out of current bug scope imo.  

And just for the record. Current bug now is present in all places where we use MultiSelect. All search pages. All filters etc.
The are safe only because almost all of them use `value` as a uniqueField by default.

**Comment by ivan-shtyrlyaev-nitka** [comment]
re `we shouldn't use VAS`
Previous implementation (using vue-multiselec) has a critical bug.  Any places are not accessible at all via keyboard.

https://github.com/politico/vue-accessible-selects/assets/64218169/bb574862-7a64-4a23-8c02-7b2d9a2b9d7f

**Comment by rbvea** [comment]
> Any places are not accessible at all via keyboard.

@ivan-shtyrlyaev-nitka forgive me for my ignorance but is that really an accessibility bug? in the sense that users can add those states through the dropdown, we're not _preventing_ them from achieving the goal. the buttons are merely a convenience

**Comment by ivan-shtyrlyaev-nitka** [comment]
> > Any places are not accessible at all via keyboard.
> 
> @ivan-shtyrlyaev-nitka forgive me for my ignorance but is that really an accessibility bug? in the sense that users can add those states through the dropdown, we're not _preventing_ them from achieving the goal. the buttons are merely a convenience.

1. In my opinion this is not a good practice to show buttons to users which are not accessible via keyboard (for keyboard users)
2. why would we start using `vue-multiselect` again knowing it has a11y bugs ? In general it has a11y issues and that's why we actually started building our own solution 

@ewalters-politico @katherinekherbert @cafloyd Could you please also add your opinion here ?

and again. Current current changes fixes a bug in all places where we use vue-accessible-select. If we agree to use vue-multiselect in https://subscriber-qared.politicopro.com/customize-news-alerts#subjects it's ok. but still we need to merge this pr

**Pull request merged**
