### PR TITLE
feature (FEP-642): Change slashes to math.div in scss mixin file

### PR DESCRIPTION
**Pull request by ee923925github**

### CODE REVIEW

**Review by hungsu — APPROVED** [review]

**Comment by hungsu** [comment]
Talking to Ben Hong about why netlify checks are failing

**Comment by hungsu** [comment]
7:22:48 AM: ERR! => Failed to build the preview
7:22:49 AM: ERR! ./.storybook/exampleMixins.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./.storybook/exampleMixins.scss)
7:22:49 AM: ERR! Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
7:22:49 AM: ERR! SassError: Undefined function.
7:22:49 AM: ERR!     ╷
7:22:49 AM: ERR! 112 │     $option-padding: math.div($spacer, 3) math.div($spacer, 1.5);
7:22:49 AM: ERR!     │                      ^^^^^^^^^^^^^^^^^^^^
7:22:49 AM: ERR!     ╵
7:22:49 AM: ERR!   src/styles/mixins.scss 112:19      selects()
7:22:49 AM: ERR!   .storybook/exampleMixins.scss 5:1  root stylesheet
7:22:49 AM: ERR! SassError: SassError: Undefined function.
7:22:49 AM: ERR!     ╷
7:22:49 AM: ERR! 112 │     $option-padding: math.div($spacer, 3) math.div($spacer, 1.5);
7:22:49 AM: ERR!     │                      ^^^^^^^^^^^^^^^^^^^^
7:22:49 AM: ERR!     ╵

**Comment by ee923925github** [comment]
@hungsu my bad. completely forgot about storybook. Added sass to dev dependencies and `additionalData` to `sass-loader`

**Review by RED143 — APPROVED** [review]

**Review by clarissastark — APPROVED** [review]
Looks good to me!

**Review by ldavidson45 — APPROVED** [review]

**Pull request merged**
