### PR TITLE
fix: update activeIndex after changing selectedIndex

### PR DESCRIPTION
**Pull request by RED143**
To cover case, when we update selected value from code and what cause the difference between indexes.

### CODE REVIEW

**Comment by jackkoppa** [comment]
Hi @RED143 - if it's not too hard, because this is a tricky problem to understand: can you include two GIFs:

one of the problem on the current main Storybook, and one showing the fix for this PR's Storybook?

Thanks!

**Comment by RED143** [comment]
@jackkoppa. To emulate changing value of select that comes from outside select, I've added several lines:
image

Without fix:
notFixed mov

With fix:
fixed mov

**Comment by jackkoppa** [comment]
Thanks @RED143 - that demo is perfect. Sounds great to me 👍

**Review by jackkoppa — APPROVED** [review]
Yup, seems good to me :+1:

@RED143, as you've continued to address particular issues w/ the select logic of `SelectSingle`, I know that `SelectMulti` does not work quite the same - it's got different handling for `active` and `selected`. That said, if you happen to be aware of `SelectMulti` experiencing similar problems at any point (not saying that's the case in this PR), please attempt to address them at the same time where possible.

Thanks as always!

**Pull request merged**
